[icedos.applications.protonvpn-cli.connect]
city = ""
country = ""
p2p = false
random = false
securecore = false
tor = false

[icedos.applications.protonvpn-cli.desktop-entry]
enable = true
countries = []

[icedos.applications.protonvpn-cli.settings.netshield]
malware = false
full = false

[icedos.applications.protonvpn-cli.settings]
anonymousCrashReports = false
customDns = false
customDnsServers = ""
ipv6 = false
killSwitch = false
moderateNat = false
portForwarding = false
vpnAccelerator = true
