[icedos.applications.zed]
autosave = false
extensions = []
extraPackages = []
fhs = false
formatOnSave = false
vim = false

[icedos.applications.zed.font]
name = "" # "" = use stylix font
size = 0 # 0 = use stylix size

[icedos.applications.zed.theme]
dark = "" # "" = use stylix theme
light = "" # "" = use stylix theme
mode = "system" # Options: 'system', 'dark', 'light'

[icedos.applications.zed.languages]

[icedos.applications.zed.lsp]
