[icedos.applications]
defaultEditor = "dev.zed.Zed.desktop"

[icedos.applications.zed]
extensions = []
extraPackages = []
fhs = false
fontSize = 16
vim = false

[icedos.applications.zed.theme]
dark = "One Dark Pro"
light = "One Light"
mode = "system" # Options: 'system', 'dark', 'light'
