[icedos.applications.nh.gc]
automatic = true
days = 0 # Number of days before a generation can be deleted
generations = 10 # Number of generations that will always be kept
interval = "Mon *-*-* 00:00:00" # Format(https://www.freedesktop.org/software/systemd/man/latest/systemd.time.html)
