[icedos.applications.mangohud]
fontSize = 20
fpsLimit = "144,0,60" # 0 equals unlimited
position = "top-left" # Options: top-left, top-right, middle-left, middle-right, bottom-left, bottom-right, top-center, bottom-center
