[icedos.applications.docker]
requireSudo = true # CAUTION: Disabling this gives every user root priviledges!

[icedos.applications.docker.daemonSettings]
fixed-cidr-v6 = "fd00::/80"
ipv6 = true
live-restore = true
