[icedos.users.username.applications.sd-inhibitor.watchers.cpu]
enable = true
threshold = 60 # CPU usage to inhibit lock in percentage

[icedos.users.username.applications.sd-inhibitor.watchers.disk]
enable = true
threshold = 10 # Disk usage to inhibit lock in MB/s

[icedos.users.username.applications.sd-inhibitor.watchers.network]
enable = true
threshold = 1_000_000 # Network usage to inhibit lock in bytes/s

[icedos.users.username.applications.sd-inhibitor.watchers.pipewire]
enable = true
inputsToIgnore = ["Noise Canceling source", "Peak detect", "cava"]
outputsToIgnore = ["Discord", "Element"]
