[icedos.applications.peon-ping.users.username]
defaultPack = "peon"
volume = 0.5
desktopNotifications = false
suppressSubagentComplete = true
packs = ["peon"]

[icedos.applications.peon-ping.users.username.categories]
