{
  # "prerelease merged with shadnet": apply the fork's P2P delta on top of the
  # pinned upstream prerelease base. Only used when BOTH prerelease and shadnet
  # are enabled; the merge patch is regenerated by update.sh's gen_merge_patch
  # whenever either pin moves (see update.sh).
  # Fail eval loudly if the patch is stale for the current pins - a moved pin
  # with an unregenerated patch otherwise surfaces as an opaque patchPhase error.
  nixpkgs.overlays =
    let
      mergeMeta = builtins.fromJSON (builtins.readFile ./shadnet-merge.json);
      pre = builtins.fromJSON (builtins.readFile ./prerelease.json);
      fork = builtins.fromJSON (builtins.readFile ./shadnet.json);
    in
    assert mergeMeta.baseRev == pre.rev;
    assert mergeMeta.forkRev == fork.rev;
    [
    (final: super: {
      shadps4 = super.shadps4.overrideAttrs (old: {
        # Mark the merged build so `shadps4.version` shows the P2P delta is in.
        # src is intentionally left as the prerelease source; only the label changes.
        __intentionallyOverridingVersion = true;
        version = "${old.version}-shadnet";
        patches = old.patches ++ [ ./shadnet-merge.patch ];
      });
    })
  ];
}
