# The nightly channel is a different application from the stable release: upstream
# rewrote spotube from Flutter to Compose Multiplatform, so its .deb is a jpackage bundle
# — bundled JRE, Skiko for rendering, vlcj for playback — laid out under /opt rather than
# /usr. Every part of nixpkgs' derivation that is specific to the Flutter build (the
# `cp -r usr/*` install, the GTK/webkitgtk deps, the mpv wrapper) therefore has to be
# replaced. All of them are plain attributes, so `overrideAttrs` still covers it and the
# pin in ./source.json stays the only thing ./update.sh has to touch.
{
  nixpkgs.overlays = [
    (
      final: prev:

      let
        inherit (final) lib;
        source = builtins.fromJSON (builtins.readFile ./source.json);
      in
      {
        spotube = prev.spotube.overrideAttrs (_: {
          inherit (source) version;

          src = final.fetchurl { inherit (source) url hash; };

          # jpackage resolves lib/app/<launcher>.cfg relative to the launcher in bin/, so
          # the bundle is copied wholesale and bin/ and lib/ stay siblings.
          installPhase = ''
            runHook preInstall

            mkdir -p $out/share/spotube
            cp -r opt/dev.krtirtho.spotube/. $out/share/spotube/

            install -Dm644 $out/share/spotube/lib/dev.krtirtho.spotube.png \
              $out/share/icons/hicolor/256x256/apps/spotube.png

            runHook postInstall
          '';

          # Replaces nixpkgs' GTK/webkitgtk set outright: this build draws through Skiko
          # (X11 + GL) and never touches the GTK stack. The bundled JRE's own libraries
          # are patched against these too.
          buildInputs = with final; [
            alsa-lib
            fontconfig
            freetype
            libGL
            libxkbcommon
            xorg.libX11
            xorg.libXext
            xorg.libXi
            xorg.libXrender
            xorg.libXtst
            zlib
          ];

          # Playback is vlcj, not mpv, and it dlopen()s libvlc by soname through JNA — so
          # libvlc has to be on LD_LIBRARY_PATH, and its plugin tree found explicitly.
          # `libvlc` rather than `vlc` keeps the Qt GUI out of the closure.
          postFixup = ''
            makeWrapper $out/share/spotube/bin/dev.krtirtho.spotube $out/bin/spotube \
              --prefix LD_LIBRARY_PATH : ${lib.makeLibraryPath [ final.libvlc ]} \
              --set-default VLC_PLUGIN_PATH ${final.libvlc}/lib/vlc/plugins \
              --prefix PATH : ${lib.makeBinPath [ final.xdg-user-dirs ]}

            # The bundled entry is generated by jpackage: reverse-DNS name, no category,
            # and absolute /opt paths that do not exist here.
            mkdir -p $out/share/applications
            substitute $out/share/spotube/lib/dev.krtirtho.spotube-dev.krtirtho.spotube.desktop \
              $out/share/applications/spotube.desktop \
              --replace-fail "Name=dev.krtirtho.spotube" "Name=Spotube" \
              --replace-fail "Comment=dev.krtirtho.spotube" "Comment=Open source Spotify client" \
              --replace-fail "Categories=Unknown" "Categories=AudioVideo;Audio;Player;" \
              --replace-fail "Exec=/opt/dev.krtirtho.spotube/bin/dev.krtirtho.spotube" "Exec=spotube" \
              --replace-fail "Icon=/opt/dev.krtirtho.spotube/lib/dev.krtirtho.spotube.png" "Icon=spotube"
          '';
        });
      }
    )
  ];
}
